name: HdkMG
on: [push]
jobs:
   hello_worlds_jobs:
      runs-on: ubuntu-latest
      steps:
         - name: Recuperation du code                                                            
            uses: actions/checkout@v4
         - name: Hello World
            run: echo "Hello World !"
