name: Github Actions
run-name: ${{ github.actor }} test
on: [push]
jobs:
   hello_worlds_jobs:
      run-on: ubuntun-latest
      steps:
         - name: recuperation du code
            uses: actions/checkout@v4
         - name: Hello world
            run: echo "Hello World !"
